### ISSUE TITLE
Filter sometimes breaks until bookmarks refreshed

### ISSUE THREAD

**Issue by pszxzsd** [SamHH/bukubrow#73]
In Chromium when I type any letter in the search field the entire popup with the bookmark entries just blanks. Fetching, adding and opening bookmarks from the unfiltered list works.
Filtering works as expected in Firefox.

Bukubrow browser extension: 2.4.2 (from the official webstore)
Bukubrow binary: compiled from current master 5b007fe
Chromium: 71.0.3578.98 (Official Build) Arch Linux (64-bit)

**Comment by SamHH** [comment]
I very occasionally encounter this issue on Firefox. I suspect it's something to do with the manner in which the bookmarks are being saved to local storage but it's hard to say; the issue is very hard to repro. I'll keep an eye out for it.

Having said that, you're building the binary on master and pairing that with the extension from the store which is at this point some distance behind master. Assuming your extension version is `2.4.2`, would you mind rebuilding against [this](https://github.com/SamHH/bukubrow/commit/369e6bdb5b85e6f9fbc3f5878af44b978c58d4c0) commit and seeing if the issues go away after a refresh?

**Comment by pszxzsd** [comment]
I tried with the binary compiled from that commit: same issue on both browsers and Firefox doesn't even work after refreshing or doesn't refresh at all, not sure.

**Comment by SamHH** [comment]
If you right click the extension icon in your toolbar and hit "Inspect pop-up", what do you see in the console? Would you mind pasting the full logs (if any) here?

**Comment by pszxzsd** [comment]
Just got around to this, the 2.5.0 version of the webext you pushed to the stores fixed this. I rebuilt the binary but I think it wasn't necessary. Search doesn't find tags, not sure if this a new issue or if it was the case before. Anyway, thank you for taking care of this!

**Comment by SamHH** [comment]
That's great!

You can search through specific fields using certain tokens, they're most easily found here: https://github.com/SamHH/bukubrow/issues/80

The UX and discoverability of these do suck a bit, I know, hence #74. :smile:
